
        self.mainLayout = QtGui.QVBoxLayout(self)
        self.mainLayout.setObjectName("mainLayout")
        self.mainGroup = QtGui.QGroupBox(self)
        self.mainGroup.setObjectName("mainGroup")
        self.mainGroupLayout = QtGui.QVBoxLayout(self.mainGroup)
        self.mainGroupLayout.setObjectName("mainGroupLayout")
        
        
        self.transformGroup = QtGui.QGroupBox(self.mainGroup)
        self.transformGroup.setFlat(True)
        self.transformGroup.setObjectName("transformGroup")
        self.transformGroupLayout = QtGui.QFormLayout(self.transformGroup)
        self.transformGroupLayout.setObjectName("transformGroupLayout")
        self.pos_label1 = QtGui.QLabel(self.transformGroup)
        self.pos_label1.setObjectName("pos_label1")
        self.transformGroupLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.pos_label1)
        self.positionWidget = QtGui.QWidget(self.transformGroup)
        self.positionWidget.setObjectName("positionWidget")
        self.postitionWidgetLayout = QtGui.QHBoxLayout(self.positionWidget)
        self.postitionWidgetLayout.setSpacing(3)
        self.postitionWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.postitionWidgetLayout.setContentsMargins(0, 0, 0, 0)
        self.postitionWidgetLayout.setObjectName("postitionWidgetLayout")
        self.pos1_edit = QtGui.QLineEdit(self.positionWidget)
        self.pos1_edit.setObjectName("pos1_edit")
        self.postitionWidgetLayout.addWidget(self.pos1_edit)
        self.pos2_edit = QtGui.QLineEdit(self.positionWidget)
        self.pos2_edit.setObjectName("pos2_edit")
        self.postitionWidgetLayout.addWidget(self.pos2_edit)
        self.transformGroupLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionWidget)
        self.widthLabel = QtGui.QLabel(self.transformGroup)
        self.widthLabel.setObjectName("widthLabel")
        self.transformGroupLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.widthLabel)
        self.widthLineEdit = QtGui.QLineEdit(self.transformGroup)
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.transformGroupLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.widthLineEdit)
        self.mainGroupLayout.addWidget(self.transformGroup)
        
        # group1
        self.colorGroup = QtGui.QGroupBox(self.mainGroup)
        self.colorGroup.setFlat(True)
        self.colorGroup.setObjectName("colorGroup")
        self.colorGroupForm = QtGui.QFormLayout(self.colorGroup)
        self.colorGroupForm.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.colorGroupForm.setObjectName("colorGroupForm")
        self.pos_label2 = QtGui.QLabel(self.colorGroup)
        self.pos_label2.setObjectName("pos_label2")
        self.colorGroupForm.setWidget(0, QtGui.QFormLayout.LabelRole, self.pos_label2)
        self.positionWidget2 = QtGui.QWidget(self.colorGroup)
        self.positionWidget2.setObjectName("positionWidget2")
        self.postitionWidget2Layout = QtGui.QHBoxLayout(self.positionWidget2)
        self.postitionWidget2Layout.setSpacing(3)
        self.postitionWidget2Layout.setContentsMargins(0, 0, 0, 0)
        self.postitionWidget2Layout.setContentsMargins(0, 0, 0, 0)
        self.postitionWidget2Layout.setObjectName("postitionWidget2Layout")
        self.pos1_edit_2 = QtGui.QLineEdit(self.positionWidget2)
        self.pos1_edit_2.setObjectName("pos1_edit_2")
        self.postitionWidget2Layout.addWidget(self.pos1_edit_2)
        self.pos2_edit_2 = QtGui.QLineEdit(self.positionWidget2)
        self.pos2_edit_2.setObjectName("pos2_edit_2")
        self.postitionWidget2Layout.addWidget(self.pos2_edit_2)
        self.colorGroupForm.setWidget(0, QtGui.QFormLayout.FieldRole, self.positionWidget2)
        self.widthLabel_2 = QtGui.QLabel(self.colorGroup)
        self.widthLabel_2.setObjectName("widthLabel_2")
        self.colorGroupForm.setWidget(1, QtGui.QFormLayout.LabelRole, self.widthLabel_2)
        self.widthLineEdit_2 = QtGui.QLineEdit(self.colorGroup)
        self.widthLineEdit_2.setObjectName("widthLineEdit_2")
        self.colorGroupForm.setWidget(1, QtGui.QFormLayout.FieldRole, self.widthLineEdit_2)
        self.mainGroupLayout.addWidget(self.colorGroup)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.mainGroupLayout.addItem(spacerItem)
        self.mainLayout.addWidget(self.mainGroup)


